version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - 5050:80

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db-mysql:/var/lib/mysql
    restart: always
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  db-postgres:
    driver: local
  db-mysql:
    driver: local

